# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jokes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jokes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bjokes.proto\x12\x05jokes\"\x1f\n\x0bJokeRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"C\n\x0cJokeResponse\x12\x0c\n\x04joke\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x14\n\x0c\x65rror_mesage\x18\x03 \x01(\t2A\n\x0b\x43huckNorris\x12\x32\n\x07GetJoke\x12\x12.jokes.JokeRequest\x1a\x13.jokes.JokeResponseB\x14\xaa\x02\x11\x43huckNorrisClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jokes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021ChuckNorrisClient'
  _globals['_JOKEREQUEST']._serialized_start=22
  _globals['_JOKEREQUEST']._serialized_end=53
  _globals['_JOKERESPONSE']._serialized_start=55
  _globals['_JOKERESPONSE']._serialized_end=122
  _globals['_CHUCKNORRIS']._serialized_start=124
  _globals['_CHUCKNORRIS']._serialized_end=189
# @@protoc_insertion_point(module_scope)
